name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # executa diariamente à meia-noite UTC
  workflow_dispatch:     # permite rodar manualmente no GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate contribution snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: adrielhs
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg

      - name: Commit and push updated snake SVGs
        uses: EndBug/add-and-commit@v9
        with:
          message: "🐍 Update contribution snake animation"
          add: "./output/*.svg"
